#!/bin/bash
set -e

if [ "${DEBUG}" = true ]; then
  set -x
fi

DEF_POSTGRESQL_HOST=
DEF_POSTGRESQL_PORT=5432
DEF_POSTGRESQL_DATABASE=postgres
DEF_POSTGRESQL_USERNAME=postgres
DEF_POSTGRESQL_PASSWORD=""

POSTGRESQL_HOST=${POSTGRESQL_HOST:-$DEF_POSTGRESQL_HOST}
POSTGRESQL_PORT=${POSTGRESQL_PORT:-$DEF_POSTGRESQL_PORT}
POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE:-$DEF_POSTGRESQL_DATABASE}
POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME:-$DEF_POSTGRESQL_USERNAME}
POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-$DEF_POSTGRESQL_PASSWORD}

exec /usr/bin/psql postgresql://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE} "$@"